
server
{
	# Port on which the server listens
	listen 4242;

	# Name accepted by the server
	server_name localhost;

	# Root directory containing all the site's files
	root ./website;

	# Default file when accessing a directory (e.g., /)
	index index.html;

	# Directory listing (autoindex) is disabled by default
	autoindex off;

	# Maximum size for the body of a request (e.g., file upload)
	client_max_body_size 10M;

	# Allowed HTTP methods for the server
	allow_methods GET POST DELETE;

	#return 301

	#  Custom error pages
	error_page 400 /errors/400.html;
	error_page 403 /errors/403.html;
	error_page 404 /errors/404.html;
	error_page 405 /errors/405.html;
	error_page 413 /errors/413.html;
	error_page 500 /errors/500.html;
	error_page 501 /errors/501.html;
	error_page 505 /errors/505.html;
	error_page 502 503 504 /errors/50x.html;

	####################################################
	# MAIN PATH (/)
	# Serves static files such as index.html, about.html, style.css
	####################################################
	location / {
		allow_methods GET POST DELETE;
		autoindex off;
	}

	####################################################
	# PATH /uploads -> VIEW uploaded files
	# Allows you to list and download files that have already been uploaded.
	####################################################
	location /uploads/ {
		allow_methods GET POST DELETE;
		autoindex on;
	}

	####################################################
	# RUTA /images
	####################################################
	location /images/ {
		allow_methods GET;
		autoindex on;
	}

	####################################################
	# CGI BLOCK
	# Here's the magic. Any request sent to /cgi-bin/
	# will be treated as a script to be executed.
	####################################################
	location /cgi-bin/ {
		allow_methods GET POST DELETE;
		cgi_pass .php /usr/bin/php-cgi;
		cgi_pass .py /usr/bin/python3;
	}
}
