server
{
    # Listen on port 443 for IPv4 and IPv6
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mzolotar.42.fr;

    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/mzolotar.crt;
    ssl_certificate_key /etc/nginx/ssl/mzolotar.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Root directory and index files
    root /var/www/html;
    index index.php index.html index.htm;

    location /
    {
        try_files $uri $uri/ =404;
    }

    # Proxy PHP requests to the WordPress container at port 9000
    location ~ \.php$
    {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

#BONUS PART:
# 1. serve static files from the static_site container
    # Redirecting traffic to the Static Bonus container
    location /static/ {
        # Rewrite the internal URL so that the static_site does not receive the /static/ prefix
        rewrite ^/static/(.*)$ /$1 break;
        
        # Forward the request directly to the `static_site` container via its internal port
        proxy_pass http://static_site:8081;
        
        # Retains the customer's original headers for security and tracking purposes
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
# 2. Adminer config:
    # We use /adminer/ to force Nginx to treat this as a folder/directory
    location /adminer/ {
        # If you use the trailing slash in proxy_pass, Nginx removes /adminer/
        # before sending it to the container (which works well with the Dockerfile)
        proxy_pass http://adminer:8080/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # This extra line is the "wizard's trick" to avoid errors if someone
    # types /adminer without the trailing slash
    location = /adminer {
        return 301 /adminer/;
    }
# 3. Catvisor config:
    location /catvisor/ {
        proxy_pass http://catvisor:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /catvisor {
        return 301 /catvisor/;
    }
}
