server {
    # Listen on port 8081 internally (so it doesn't conflict with the main NGINX server)
    listen 8081;
    server_name localhost;

    # Root directory where we will map your public folder
    root /var/www/static;
    index index.html;

    # Basic routing
    location / {
        try_files $uri $uri/ =404;
    }

    # Surgical block for mapping your custom error pages
    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 502 503 504 /errors/50x.html;
    error_page 501 /errors/501.html;
    error_page 505 /errors/505.html;


    # Ensure NGINX can correctly access the error folder
    location /errors/ {
        # internal;
    }

	# Images
	location /assets/images/ {
        limit_except GET {
            deny all;
        }
        autoindex on;
    }
}